apiVersion: apps/v1
kind: Deployment
metadata:
  name: manifest-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: manifest
  template:
    metadata:
      labels:
        app: manifest
    spec:
      containers:
      - name: manifest
        image: reto3:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
        volumeMounts:
        - name: notes-volume
          mountPath: /data
      volumes:
      - name: notes-volume
        emptyDir: {}
